"""add reference storage metadata

Revision ID: 3b11a38ae86f
Revises: 87a21d8e3887
Create Date: 2026-09-11 16:05:15.345872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b11a38ae86f'
down_revision: Union[str, Sequence[str], None] = '87a21d8e3887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sha256', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('size_bytes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_documents', schema=None) as batch_op:
        batch_op.drop_column('mime_type')
        batch_op.drop_column('size_bytes')
        batch_op.drop_column('sha256')
        batch_op.drop_column('storage_key')

    # ### end Alembic commands ###
