"""initial ForensiQ schema

Revision ID: 87a21d8e3887
Revises: 
Create Date: 2026-09-11 15:16:18.016639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a21d8e3887'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('pii_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.String(), nullable=True),
    sa.Column('best_match_document_id', sa.String(), nullable=True),
    sa.Column('best_match_filename', sa.String(), nullable=True),
    sa.Column('best_match_score', sa.String(), nullable=True),
    sa.Column('matches_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_history_id'), ['id'], unique=False)

    op.create_table('reference_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('pii_entities_json', sa.Text(), nullable=True),
    sa.Column('fingerprint_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reference_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_documents_document_id'), ['document_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reference_documents_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('reference_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_documents_id'))
        batch_op.drop_index(batch_op.f('ix_reference_documents_document_id'))

    op.drop_table('reference_documents')
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_history_id'))

    op.drop_table('analysis_history')
    # ### end Alembic commands ###
